import type { AdminBootstrap } from "@shared/admin";

const now = new Date();
const daysAgo = (days: number, hour = 10) => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

export const adminMockData: AdminBootstrap = {
  dashboard: {
    stats: {
      totalListings: 12,
      activeListings: 9,
      unreadMessages: 4,
      trafficToday: 286,
      trafficChange: 18.4,
    },
    traffic: [
      { day: "Po", visits: 164 },
      { day: "Út", visits: 198 },
      { day: "St", visits: 176 },
      { day: "Čt", visits: 246 },
      { day: "Pá", visits: 218 },
      { day: "So", visits: 297 },
      { day: "Ne", visits: 286 },
    ],
    recentListings: [],
  },
  cars: [
    {
      id: "car-audi-a6",
      title: "Audi A6 Avant 45 TDI quattro",
      make: "Audi",
      model: "A6 Avant",
      price: 829000,
      currency: "Kč",
      year: 2021,
      mileage: 68400,
      fuel: "Nafta",
      transmission: "Automatická",
      power: "180 kW",
      description: "Pravidelně servisovaný vůz s jasnou historií a bohatou výbavou.",
      photoUrl: "/assets/k2-hero-import.webp",
      status: "available",
      featured: true,
      createdAt: daysAgo(1),
      updatedAt: daysAgo(0),
    },
    {
      id: "car-volvo-xc60",
      title: "Volvo XC60 B4 AWD Inscription",
      make: "Volvo",
      model: "XC60",
      price: 968000,
      currency: "Kč",
      year: 2022,
      mileage: 41500,
      fuel: "Diesel",
      transmission: "Automatická",
      power: "145 kW",
      description: "Komfortní SUV po prvním majiteli, kompletní servisní historie.",
      photoUrl: "/assets/k2-hero-inspection.webp",
      status: "available",
      featured: false,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
    },
    {
      id: "car-bmw-330",
      title: "BMW 330i Touring M Sport",
      make: "BMW",
      model: "330i Touring",
      price: 745000,
      currency: "Kč",
      year: 2020,
      mileage: 79200,
      fuel: "Benzín",
      transmission: "Automatická",
      power: "190 kW",
      description: "Dynamické kombi s pohonem zadních kol a sportovním paketem M.",
      photoUrl: "/assets/k2-hero-workshop.webp",
      status: "sold",
      featured: false,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(5),
    },
  ],
  messages: [
    {
      id: "msg-1",
      name: "Tomáš Malý",
      email: "tomas.maly@example.cz",
      phone: "+420 602 123 456",
      subject: "Dotaz k Audi A6 Avant",
      message: "Dobrý den, je Audi stále k dispozici? Měl bych zájem o prohlídku tento týden.",
      source: "listing",
      status: "unread",
      createdAt: daysAgo(0, 9),
    },
    {
      id: "msg-2",
      name: "Petra Nováková",
      email: "petra.novakova@example.cz",
      phone: "+420 731 987 654",
      subject: "Poptávka kontroly vozu",
      message: "Potřebovala bych prověřit vůz před koupí v Olomouci. Je možné se domluvit na pátek?",
      source: "reservation",
      status: "unread",
      createdAt: daysAgo(0, 8),
    },
    {
      id: "msg-3",
      name: "Jan Dvořák",
      email: "jan.dvorak@example.cz",
      subject: "Dovoz vozu z Německa",
      message: "Hledám Volvo XC60 do 900 tisíc. Nabízíte i pomoc s dovozem a prověřením historie?",
      source: "contact",
      status: "read",
      createdAt: daysAgo(1, 14),
    },
    {
      id: "msg-4",
      name: "Andrea Veselá",
      email: "andrea.vesela@example.cz",
      phone: "+420 777 140 112",
      subject: "Zkušební jízda",
      message: "Prosím o informaci, zda se lze objednat na zkušební jízdu s Volvo XC60 během soboty.",
      source: "listing",
      status: "unread",
      createdAt: daysAgo(1, 11),
    },
  ],
  pricing: [
    {
      id: "pricing-inspection",
      title: "Kontrola vozu před koupí",
      description: "Technik přijede k vybranému vozu a srozumitelně vysvětlí, co našel.",
      priceLabel: "od 3 490 Kč",
      highlighted: true,
      sortOrder: 1,
      features: ["Kontrola konkrétního vozu", "Závady a riziková místa", "Jasné doporučení před koupí"],
      updatedAt: daysAgo(3),
    },
    {
      id: "pricing-import",
      title: "Prověření a dovoz vozu",
      description: "Pomoc s výběrem, prověřením nabídky a dalším postupem při dovozu.",
      priceLabel: "od 2 490 Kč",
      highlighted: false,
      sortOrder: 2,
      features: ["Prověření vybrané nabídky", "Doporučení dalšího postupu", "Individuální rozsah"],
      updatedAt: daysAgo(4),
    },
    {
      id: "pricing-detailing",
      title: "Detailing interiéru",
      description: "Důkladná péče o čistší interiér a lepší pocit z každé jízdy.",
      priceLabel: "od 2 490 Kč",
      highlighted: false,
      sortOrder: 3,
      features: ["Hloubkové čištění", "Péče podle stavu", "Individuální rozsah"],
      updatedAt: daysAgo(7),
    },
  ],
  settings: {
    id: "site",
    siteName: "K2 garage",
    logoUrl: "/assets/K2-GARAGE-mlecna.webp",
    faviconUrl: "/assets/favicon.ico",
    email: "k2garage@seznam.cz",
    phone: "+420 725 480 018",
    facebookUrl: "https://www.facebook.com/",
    instagramUrl: "https://www.instagram.com/",
    youtubeUrl: "",
    updatedAt: daysAgo(1),
  },
};

adminMockData.dashboard.recentListings = adminMockData.cars.slice(0, 3);
